[project]
authors = ["Caryn Geady <caryn@geady.com>"]
channels = ["conda-forge"]
name = "BINF-5507-Winter-2026"
platforms = ["osx-arm64", "win-64", "linux-64", "osx-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "<3.14"
numpy = ">=2.4.1,<3"
pandas = ">=2.3.3,<3"
ipykernel = ">=7.1.0,<8"
